---
title: "economy"
output: html_document
date: "2023-07-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

```{r}
data <- read.csv("/Users/jianingcai/Downloads/Economy_compilation.csv")
```

```{r}
#distinct_count <- table(data$Sub.categories)
#distinct_count
```

```{r}
data$Sub.categories = tolower(data$Sub.categories)
```

```{r}
employment = 0
lf = 0
wage = 0
income = 0
tax = 0
job = 0
economy = 0
for (i in data$Sub.categories){
  #if (any(grepl("Employment", i))){
  # employment = employment + 1
  #}
  if (any(grepl("employment", i))){
    employment = employment + 1
  }
  if (any(grepl("labor force", i))){
    lf = lf + 1
  }
  #if (any(grepl("Labor force", i))){
   # lf = lf + 1
  #}
  if (any(grepl("wage", i))){
    wage = wage + 1
  }
  #if (any(grepl("Wage", i))){
  #  wage = wage + 1
  #}
  if (any(grepl("job", i))){
    job = job + 1
  }
  #if (any(grepl("Job", i))){
  #  job = job + 1
  #}
  if (any(grepl("tax", i))){
    tax = tax + 1
  }
 # if (any(grepl("Tax", i))){
  #  tax = tax + 1
  #}
  if (any(grepl("income", i))){
    income = income + 1
  }
  #if (any(grepl("Income", i))){
  #  income = income + 1
  #}
  #if (any(grepl("Economy", i))){
  #  economy = economy + 1
  #}
  if (any(grepl("economy", i))){
    economy = economy + 1
  }
}

category <- c("employment", "income", "tax", "labor force", "wage", "job","economy")
counts <- c(employment, income, tax, lf, wage, job,economy)
total_df = data.frame(category, counts)

barplot(counts, names.arg = category, col = "steelblue", main = "Distribution of Data Tools' Category(All States)", xlab = "Category", ylab = "counts", cex.names = 0.9, ylim = c(0,60))
text(x = c(0.7, 1.9, 3.1, 4.3, 5.5, 6.7, 7.9), y = counts, labels = counts, pos = 3, cex = 0.8, col = "black")
```



------------specific state's result----------------
```{r}
employment = 0
lf = 0
wage = 0
income = 0
tax = 0
job = 0
economy = 0
for (i in data$Sub.categories[data$State..Country == "California"]){
  if (any(grepl("Employment", i))){
    employment = employment + 1
  }
  if (any(grepl("employment", i))){
    employment = employment + 1
  }
  if (any(grepl("labor force", i))){
    lf = lf + 1
  }
  if (any(grepl("Labor force", i))){
    lf = lf + 1
  }
  if (any(grepl("wage", i))){
    wage = wage + 1
  }
  if (any(grepl("Wage", i))){
    wage = wage + 1
  }
  if (any(grepl("job", i))){
    job = job + 1
  }
  if (any(grepl("Job", i))){
    job = job + 1
  }
  if (any(grepl("tax", i))){
    tax = tax + 1
  }
  if (any(grepl("Tax", i))){
    tax = tax + 1
  }
  if (any(grepl("income", i))){
    income = income + 1
  }
  if (any(grepl("Income", i))){
    income = income + 1
  }
  if (any(grepl("Economy", i))){
    economy = economy + 1
  }
  if (any(grepl("economy", i))){
    economy = economy + 1
  }
}

category <- c("employment", "income", "tax", "labor force", "wage", "job","economy")
counts <- c(employment, income, tax, lf, wage, job,economy)
total_df = data.frame(category, counts)

barplot(counts, names.arg = category, col = "steelblue", main = "Distribution of Data Tools' Category(All States)", xlab = "Category", ylab = "counts", cex.names = 0.9, ylim = c(0,60))
text(x = c(0.7, 1.9, 3.1, 4.3, 5.5, 6.7, 7.9), y = counts, labels = counts, pos = 3, cex = 0.8, col = "black")
```




